- name: Create docker and push
  hosts: JB-Ubuntu
  become: True
  tasks:
  - name: copy promtheus yml file 
    copy: 
     src: /jb-ansible/workspace/optit/prometheus.yml
     dest: /opt/
     remote_src: True
  - name: copy docker file
    copy:
     src: /jb-ansible/workspace/optit/Dockerfile
     dest: /opt/
     remote_src: True
  - name: Create docker image
    docker_image:
     path: /opt/
     name: jb_prometheus
   
