- name: Create docker and push
  hosts: JB-Ubuntu
  become: True
  tasks:
  - name: copy promtheus yml file 
    copy: 
     src: prometheus.yml
     dest: /opt/
  - name: copy docker file
    copy:
     src: Dockerfile
     dest: /opt/
  - name: Create docker image
    docker_image:
     dockerfile: /opt/Dockerfile
     name: jb_prometheus
   
