- name: Create docker and push
  hosts: JB-Ubuntu
  become: True
  tasks:
  - name: copy promtheus yml file 
    copy: 
     src: prometheus.yml
     dest: /opt/
  - name: copy docker file
    copy:
     src: Dockerfile
     dest: /opt/
  - name: Create docker image
    docker_image:
     path: /opt/
     name: jb_prometheus
     tag: v2.0
  - name: Log into DockerHub
    docker_login:
     username: jangbsingh
     password: Jang@7376
     email: jangbahadur0@gmail.com
  - name: Tag and push to docker hub
    docker_image:
     name: jb_prometheus
     repository: jangbsingh/jb_prometheus 
     tag: latest
     push: yes
  - name: remove image 
    docker_image:
     state: absent
     name: jangbsingh/jb_prometheus
     tag: latest
  - name: pull image
    docker_image:
     name: jangbsingh/jb_prometheus:latest
  
