- name: "grafana installation"
  hosts: JB-Ubuntu
  become: True
  tasks:
  - name: add system user
    user:
     name: grafana
     system: True
     comment: grafana nologin User
     shell: /usr/sbin/nologin
     create_home: False
  - name: "Install grafana"
    unarchive:
     src: https://dl.grafana.com/oss/release/grafana-7.1.5.linux-amd64.tar.gz
     dest: /opt/
     remote_src: True
  - name: Copy grafana file to bin
    copy:
     src: /opt/grafana-7.1.5/bin/grafana-server
     dest: /usr/local/bin/
     owner: grafana
     group: grafana
     mode: 0755
     remote_src: True
  - name: Copy grafana file to DATA
    copy:
     src: /opt/grafana-7.1.5/.
     dest: /etc/grafana/
     owner: grafana
     group: grafana
     mode: 0755
     remote_src: True
  - name: Delete grafana
    file:
     path: /etc/grafana/bin/grafana-server
     state: absent
  - name: Delete grafana opt folder
    file:
     path: /opt/grafana-7.1.5
     state: absent

  - name: Copy systemd init file
    template:
     src: grafana.service_j1
     dest: /etc/systemd/system/grafana.service
  - name: Start grafana service
    systemd:
     name: grafana
     daemon_reload: True
     state: started
     enabled: yes
