- name: copy kube yml file
  hosts: JB-Centos-jenkins
  become: True
  tasks:
  - name: copy nginx deplyment yml file 
    copy: 
     src: nginx_deployment.yml
     dest: /opt/
  - name: copy nginx service yml file
    copy:
     src: nginx_service.yml
     dest: /opt/
  
