- name: copy kube yml file
  hosts: JB-local
  become: True
  tasks:
  - name: copy nginx deplyment yml file 
    copy: 
     src: nginx_deployment.yml
     dest: /opt/
  - name: copy nginx service yml file
    copy:
     src: nginx_service.yml
     dest: /opt/
  - name: copy tomcat deplyment yml file 
    copy: 
     src: tomcat_deployment.yml
     dest: /opt/
  - name: copy tomcat service yml file
    copy:
     src: tomcat_service.yml
     dest: /opt/
  - name: Export environment variable
    shell: export KUBECONFIG=/home/optit/Downloads/civo-k83-kubeconfig 
