- name: "node_exporter installation"
  hosts: all
  become: True
  tasks:
  - name: add system user
    user:
     name: node_exporter
     system: True
     comment: node_exporter nologin User
     shell: /usr/sbin/nologin
     create_home: False
  - name: "Install node_exporter"
    unarchive:
     src: "https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz"
     dest: /opt/
     remote_src: True
  - name: Copy node_exporter file to bin
    copy:
     src: /opt/node_exporter-1.0.1.linux-amd64/node_exporter
     dest: /usr/local/bin/
     owner: node_exporter
     group: node_exporter
     mode: 0755
     remote_src: True
  - name: Delete node exporter opt folder
    file:
     path: /opt/node_exporter-1.0.1.linux-amd64
     state: absent

  - name: Copy systemd init file
    template:
     src: node_exporter.service_j1
     dest: /etc/systemd/system/node_exporter.service
     owner: node_exporter
     group: node_exporter
  - name: Start node_exporter service
    systemd:
     name: node_exporter
     daemon_reload: True
     state: started
     enabled: True

